name: 'Build'
inputs:
  output:
    required: true
runs:
  using: "composite"
  steps:
    - name: Restore vcpkg binary cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: vcpkg-bin-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          vcpkg-bin-${{ runner.os }}-
    - name: build
      env:
        VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/vcpkg_cache,readwrite"
      shell: bash
      run: bash ./resource/builder.sh
    - uses: actions/upload-artifact@v4
      if: ${{ runner.os == 'Windows' }}
      with:
        name: ${{ inputs.output }}
        path: build/comic_reader-win64.zip
    - uses: actions/upload-artifact@v4
      if: ${{ runner.os == 'Linux' }}
      with:
        name: ${{ inputs.output }}
        path: |
          build/Comic_Reader-x86_64.AppImage
          build/Comic_Reader-x86_64.AppImage.zsync
