name: Build
on: 
  push:
    branches:
      - '**'        # matches every branch
      - '!master'
jobs:
  build-release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
      - run: ./build.sh macos
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/ComicReaderMac.zip
  build-release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: ./build.sh windows
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: ComicReaderWin.zip
  