name: CI
on: 
  push:
    branches:
      - '**'        # matches every branch
      - '!master'
    tags:
      - '**'        # matches every tag
defaults:
  run:
    shell: bash
jobs:
  build-windows:
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: './.github/workflows/setup'
        with:
          zip-output: windows-zip 
  build-linux:
    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
    runs-on: ubuntu-latest
    steps:
      - name: Install wxWidgets
        run: sudo apt update && sudo apt install -y x11-xserver-utils libxi-dev libxtst-dev python3-jinja2 libxrandr-dev 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: './.github/workflows/setup'
        with:
          zip-output: linux-zip 
    
  create-release:
    # if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build-windows
      - build-linux
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: windows-zip
      - uses: actions/download-artifact@v3
        with:
          name: linux-zip
      - run: ls
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            comic_reader-*.zip
