name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  # build-release-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         architecture: x64
  #         channel: 'stable'
  #     - run: flutter config --enable-macos-desktop
  #     - run: flutter precache
  #     - run: flutter build macos --release
  #     - run: (cd build/macos/Build/Products/Release/ && zip -r ComicReaderMac.zip "Comic Reader.app")
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: macos-build
  #         path: build/macos/Build/Products/Release/ComicReaderMac.zip
  build-release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Test
        run: echo %ACTIONS_CACHE_URL%
      - uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: ComicReaderWin.zip
  create-release:
    needs:
      - build-release-windows
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: windows-build
      - run: ls
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ComicReaderWin.zip
