name: Build Release
on:
  push:
    tags:
      - "v*"
jobs:
  create-release:
    needs:
      - build-release-macos
      - build-release-windows
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: macos-build
      - uses: actions/download-artifact@v3
        with:
          name: windows-build
      - run: ls
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ComicReaderMac.zip
            ComicReaderWin.zip
