name: Build Release
on:
  push:
    branches:
      - master
      - feature/windows-build
jobs:
  build-release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          flutter-version: "3.3.7"
      - run: flutter config --enable-macos-desktop
      - run: flutter precache
      - run: flutter build macos --release
      - run: (cd build/macos/Build/Products/Release/ && zip -r ComicReaderMac.zip "Comic Reader.app")
      - uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/ComicReaderMac.zip
  build-release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.7"
      - run: flutter config --enable-windows-desktop
      - run: flutter precache
      - run: flutter build windows --release
      - run: 7z a ComicReaderWin.zip ./build/windows/runner/Release/*
      - uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: ComicReaderWin.zip
  create-release:
    needs:
      - build-release-macos
      - build-release-windows
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: macos-build
      - uses: actions/download-artifact@v3
        with:
          name: windows-build
      - run: ls
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ComicReaderMac.zip
            ComicReaderWin.zip
